{{- $fullname := include "tekmetric-app.fullname" . }}

{{- range $nameSuffix, $secret := .Values.secrets }}
{{- if $secret.data }}
{{- $name := default (printf "%s-%s" $fullname $nameSuffix) $secret.name }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ (tpl $name $) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "tekmetric-app.labels" $ | nindent 4 }}
  {{- with .annotations }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- $secret.data | toYaml | nindent 2 }}
{{- end -}}
{{- end -}}